name: Deploy to VPS

on:
  push:
    branches:
      - main  # или master, если у тебя ветка называется так

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ssh
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          echo "=== Подключение к серверу ==="
          ssh -v ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            cd /home/deploy/my-app
            
            if [ ! -d ".git" ]; then
              echo "Клонируем репозиторий..."
              git clone git@github.com:S25AI/guestbookApp.git .
            else
              echo "Обновляем существующий репозиторий..."
              git pull origin main
            fi

            echo "Запуск docker compose..."
            docker compose up -d --build --remove-orphans
          EOF